{"name": "test_login[case3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 != 2", "trace": "self = <TestCases.pytest.test_dome.TestLogin object at 0x00000229B11025F8>\ncase = {'expect_data': '{\"code\": 2,\"msg\": \"账号不存在.\"}', 'id': 4, 'method': 'post', 'request_data': '{\"account\":\"lin123456\",\"pwd\":\"afd84507f0394b705272e2434e5ec8f7f46967609ff772cdeba6d5543fff3aea\"}', ...}\n\n    def test_login(self,case):\n        print(\"执行第{}条用例：{}\".format(case[\"id\"], case[\"title\"]))\n        print(\"测试数据为：\",case)\n    \n        respon = send_requests(case[\"method\"], case[\"url\"], data=case[\"request_data\"])\n        print(\"测试结果为：\", respon.json())\n        expect_data = json.loads(case[\"expect_data\"])\n        try:\n>           assert respon.json()[\"code\"]!=expect_data[\"code\"]\nE           assert 2 != 2\n\nTestCases\\pytest\\test_dome.py:30: AssertionError"}, "parameters": [{"name": "case", "value": "{'id': 4, 'title': '登录失败-账号未注册', 'method': 'post', 'url': '/kvp_mps/v1/login', 'request_data': '{\"account\":\"lin123456\",\"pwd\":\"afd84507f0394b705272e2434e5ec8f7f46967609ff772cdeba6d5543fff3aea\"}', 'expect_data': '{\"code\": 2,\"msg\": \"账号不存在.\"}'}"}], "start": 1597993338525, "stop": 1597993338616, "uuid": "979292db-d33f-4b3e-8771-d6bd12a04694", "historyId": "39cbab9e6662fc58e41eccbebc732aa3", "testCaseId": "3508b8cb4a6f338d1140ad49bea185dd", "fullName": "TestCases.pytest.test_dome.TestLogin#test_login", "labels": [{"name": "parentSuite", "value": "TestCases.pytest"}, {"name": "suite", "value": "test_dome"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "KST-CSB-lintt"}, {"name": "thread", "value": "39736-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.pytest.test_dome"}]}