{"name": "test_login[case1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 != 1", "trace": "self = <TestCases.pytest.test_dome.TestLogin object at 0x0000024EB0C7AEB8>\ncase = {'expect_data': '{\"code\": 1,\"msg\": \"参数为空，校验失败.\"}', 'id': 2, 'method': 'post', 'request_data': '{\"account\":\"\",\"pwd\":\"afd84507f0394b705272e2434e5ec8f7f46967609ff772cdeba6d5543fff3aea\"}', ...}\n\n    def test_login(self,case):\n        print(\"执行第{}条用例：{}\".format(case[\"id\"], case[\"title\"]))\n        print(\"测试数据为：\",case)\n    \n        respon = send_requests(case[\"method\"], case[\"url\"], data=case[\"request_data\"])\n        print(\"测试结果为：\", respon.json())\n        expect_data = json.loads(case[\"expect_data\"])\n        try:\n>           assert respon.json()[\"code\"]!=expect_data[\"code\"]\nE           assert 1 != 1\n\nTestCases\\pytest\\test_dome.py:30: AssertionError"}, "parameters": [{"name": "case", "value": "{'id': 2, 'title': '登录失败-用户名为空', 'method': 'post', 'url': '/kvp_mps/v1/login', 'request_data': '{\"account\":\"\",\"pwd\":\"afd84507f0394b705272e2434e5ec8f7f46967609ff772cdeba6d5543fff3aea\"}', 'expect_data': '{\"code\": 1,\"msg\": \"参数为空，校验失败.\"}'}"}], "start": 1597981891826, "stop": 1597981891915, "uuid": "e0ef212d-041e-4793-8960-002efcac0c9c", "historyId": "20b7d6c660b11e5cfe7636ba035bdb6d", "testCaseId": "3508b8cb4a6f338d1140ad49bea185dd", "fullName": "TestCases.pytest.test_dome.TestLogin#test_login", "labels": [{"name": "parentSuite", "value": "TestCases.pytest"}, {"name": "suite", "value": "test_dome"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "KST-CSB-lintt"}, {"name": "thread", "value": "43140-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.pytest.test_dome"}]}